@startuml
actor Eleve
participant "Système d'inscription" as SI
participant "Adresse"
actor "Directeur"
participant "Cours"

activate Eleve
activate SI
Eleve -> SI : saisir données personnelles
activate Adresse
SI -> Adresse : saisir adresse
Adresse -> Adresse : valider format code postal
Adresse --> SI : résultat validation
Deactivate Adresse

alt Adresse valide
activate Directeur
    SI -> Directeur : demande d'autorisation
    Directeur --> SI : autorisé / refusé
    alt Autorisé
        SI -> SI : ajouter élève et adresse
        SI --> Eleve : confirmation d'inscription
    else Refusé
        SI --> Eleve : inscription refusée
    end
else Adresse invalide
    SI --> Eleve : message d'erreur de saisie adresse
end

Directeur -> Cours : assignation de l'élève a des cours


@enduml